// Country name + matching nationality/demonym + ISO 3166-1 alpha-2 code
// (for the flag icon), used to power autocomplete on the Location and
// Nationality profile fields. Neither field is restricted to this list
// server-side — it's suggestions, not an enum — so a value typed here that
// doesn't match anything is still saved as-is (just without a flag).
export interface CountryEntry {
  country: string;
  nationality: string;
  code: string;
}

export const COUNTRIES: CountryEntry[] = [
  { country: 'Afghanistan', nationality: 'Afghan', code: 'AF' },
  { country: 'Albania', nationality: 'Albanian', code: 'AL' },
  { country: 'Algeria', nationality: 'Algerian', code: 'DZ' },
  { country: 'Andorra', nationality: 'Andorran', code: 'AD' },
  { country: 'Angola', nationality: 'Angolan', code: 'AO' },
  { country: 'Argentina', nationality: 'Argentine', code: 'AR' },
  { country: 'Armenia', nationality: 'Armenian', code: 'AM' },
  { country: 'Australia', nationality: 'Australian', code: 'AU' },
  { country: 'Austria', nationality: 'Austrian', code: 'AT' },
  { country: 'Azerbaijan', nationality: 'Azerbaijani', code: 'AZ' },
  { country: 'Bahamas', nationality: 'Bahamian', code: 'BS' },
  { country: 'Bahrain', nationality: 'Bahraini', code: 'BH' },
  { country: 'Bangladesh', nationality: 'Bangladeshi', code: 'BD' },
  { country: 'Barbados', nationality: 'Barbadian', code: 'BB' },
  { country: 'Belarus', nationality: 'Belarusian', code: 'BY' },
  { country: 'Belgium', nationality: 'Belgian', code: 'BE' },
  { country: 'Belize', nationality: 'Belizean', code: 'BZ' },
  { country: 'Benin', nationality: 'Beninese', code: 'BJ' },
  { country: 'Bhutan', nationality: 'Bhutanese', code: 'BT' },
  { country: 'Bolivia', nationality: 'Bolivian', code: 'BO' },
  { country: 'Bosnia and Herzegovina', nationality: 'Bosnian', code: 'BA' },
  { country: 'Botswana', nationality: 'Motswana', code: 'BW' },
  { country: 'Brazil', nationality: 'Brazilian', code: 'BR' },
  { country: 'Brunei', nationality: 'Bruneian', code: 'BN' },
  { country: 'Bulgaria', nationality: 'Bulgarian', code: 'BG' },
  { country: 'Burkina Faso', nationality: 'Burkinabe', code: 'BF' },
  { country: 'Burundi', nationality: 'Burundian', code: 'BI' },
  { country: 'Cambodia', nationality: 'Cambodian', code: 'KH' },
  { country: 'Cameroon', nationality: 'Cameroonian', code: 'CM' },
  { country: 'Canada', nationality: 'Canadian', code: 'CA' },
  { country: 'Chile', nationality: 'Chilean', code: 'CL' },
  { country: 'China', nationality: 'Chinese', code: 'CN' },
  { country: 'Colombia', nationality: 'Colombian', code: 'CO' },
  { country: 'Costa Rica', nationality: 'Costa Rican', code: 'CR' },
  { country: 'Croatia', nationality: 'Croatian', code: 'HR' },
  { country: 'Cuba', nationality: 'Cuban', code: 'CU' },
  { country: 'Cyprus', nationality: 'Cypriot', code: 'CY' },
  { country: 'Czechia', nationality: 'Czech', code: 'CZ' },
  { country: 'Denmark', nationality: 'Danish', code: 'DK' },
  { country: 'Dominican Republic', nationality: 'Dominican', code: 'DO' },
  { country: 'Ecuador', nationality: 'Ecuadorian', code: 'EC' },
  { country: 'Egypt', nationality: 'Egyptian', code: 'EG' },
  { country: 'El Salvador', nationality: 'Salvadoran', code: 'SV' },
  { country: 'Estonia', nationality: 'Estonian', code: 'EE' },
  { country: 'Ethiopia', nationality: 'Ethiopian', code: 'ET' },
  { country: 'Fiji', nationality: 'Fijian', code: 'FJ' },
  { country: 'Finland', nationality: 'Finnish', code: 'FI' },
  { country: 'France', nationality: 'French', code: 'FR' },
  { country: 'Georgia', nationality: 'Georgian', code: 'GE' },
  { country: 'Germany', nationality: 'German', code: 'DE' },
  { country: 'Ghana', nationality: 'Ghanaian', code: 'GH' },
  { country: 'Greece', nationality: 'Greek', code: 'GR' },
  { country: 'Guatemala', nationality: 'Guatemalan', code: 'GT' },
  { country: 'Haiti', nationality: 'Haitian', code: 'HT' },
  { country: 'Honduras', nationality: 'Honduran', code: 'HN' },
  { country: 'Hong Kong', nationality: 'Hong Konger', code: 'HK' },
  { country: 'Hungary', nationality: 'Hungarian', code: 'HU' },
  { country: 'Iceland', nationality: 'Icelandic', code: 'IS' },
  { country: 'India', nationality: 'Indian', code: 'IN' },
  { country: 'Indonesia', nationality: 'Indonesian', code: 'ID' },
  { country: 'Iran', nationality: 'Iranian', code: 'IR' },
  { country: 'Iraq', nationality: 'Iraqi', code: 'IQ' },
  { country: 'Ireland', nationality: 'Irish', code: 'IE' },
  { country: 'Israel', nationality: 'Israeli', code: 'IL' },
  { country: 'Italy', nationality: 'Italian', code: 'IT' },
  { country: 'Jamaica', nationality: 'Jamaican', code: 'JM' },
  { country: 'Japan', nationality: 'Japanese', code: 'JP' },
  { country: 'Jordan', nationality: 'Jordanian', code: 'JO' },
  { country: 'Kazakhstan', nationality: 'Kazakhstani', code: 'KZ' },
  { country: 'Kenya', nationality: 'Kenyan', code: 'KE' },
  { country: 'Kuwait', nationality: 'Kuwaiti', code: 'KW' },
  { country: 'Kyrgyzstan', nationality: 'Kyrgyz', code: 'KG' },
  { country: 'Laos', nationality: 'Lao', code: 'LA' },
  { country: 'Latvia', nationality: 'Latvian', code: 'LV' },
  { country: 'Lebanon', nationality: 'Lebanese', code: 'LB' },
  { country: 'Libya', nationality: 'Libyan', code: 'LY' },
  { country: 'Liechtenstein', nationality: 'Liechtensteiner', code: 'LI' },
  { country: 'Lithuania', nationality: 'Lithuanian', code: 'LT' },
  { country: 'Luxembourg', nationality: 'Luxembourgish', code: 'LU' },
  { country: 'Madagascar', nationality: 'Malagasy', code: 'MG' },
  { country: 'Malaysia', nationality: 'Malaysian', code: 'MY' },
  { country: 'Maldives', nationality: 'Maldivian', code: 'MV' },
  { country: 'Mali', nationality: 'Malian', code: 'ML' },
  { country: 'Malta', nationality: 'Maltese', code: 'MT' },
  { country: 'Mexico', nationality: 'Mexican', code: 'MX' },
  { country: 'Moldova', nationality: 'Moldovan', code: 'MD' },
  { country: 'Monaco', nationality: 'Monegasque', code: 'MC' },
  { country: 'Mongolia', nationality: 'Mongolian', code: 'MN' },
  { country: 'Montenegro', nationality: 'Montenegrin', code: 'ME' },
  { country: 'Morocco', nationality: 'Moroccan', code: 'MA' },
  { country: 'Mozambique', nationality: 'Mozambican', code: 'MZ' },
  { country: 'Myanmar', nationality: 'Burmese', code: 'MM' },
  { country: 'Namibia', nationality: 'Namibian', code: 'NA' },
  { country: 'Nepal', nationality: 'Nepali', code: 'NP' },
  { country: 'Netherlands', nationality: 'Dutch', code: 'NL' },
  { country: 'New Zealand', nationality: 'New Zealander', code: 'NZ' },
  { country: 'Nicaragua', nationality: 'Nicaraguan', code: 'NI' },
  { country: 'Nigeria', nationality: 'Nigerian', code: 'NG' },
  { country: 'North Korea', nationality: 'North Korean', code: 'KP' },
  { country: 'North Macedonia', nationality: 'Macedonian', code: 'MK' },
  { country: 'Norway', nationality: 'Norwegian', code: 'NO' },
  { country: 'Oman', nationality: 'Omani', code: 'OM' },
  { country: 'Pakistan', nationality: 'Pakistani', code: 'PK' },
  { country: 'Panama', nationality: 'Panamanian', code: 'PA' },
  { country: 'Papua New Guinea', nationality: 'Papua New Guinean', code: 'PG' },
  { country: 'Paraguay', nationality: 'Paraguayan', code: 'PY' },
  { country: 'Peru', nationality: 'Peruvian', code: 'PE' },
  { country: 'Philippines', nationality: 'Filipino', code: 'PH' },
  { country: 'Poland', nationality: 'Polish', code: 'PL' },
  { country: 'Portugal', nationality: 'Portuguese', code: 'PT' },
  { country: 'Qatar', nationality: 'Qatari', code: 'QA' },
  { country: 'Romania', nationality: 'Romanian', code: 'RO' },
  { country: 'Russia', nationality: 'Russian', code: 'RU' },
  { country: 'Rwanda', nationality: 'Rwandan', code: 'RW' },
  { country: 'Samoa', nationality: 'Samoan', code: 'WS' },
  { country: 'Saudi Arabia', nationality: 'Saudi', code: 'SA' },
  { country: 'Senegal', nationality: 'Senegalese', code: 'SN' },
  { country: 'Serbia', nationality: 'Serbian', code: 'RS' },
  { country: 'Singapore', nationality: 'Singaporean', code: 'SG' },
  { country: 'Slovakia', nationality: 'Slovak', code: 'SK' },
  { country: 'Slovenia', nationality: 'Slovenian', code: 'SI' },
  { country: 'South Africa', nationality: 'South African', code: 'ZA' },
  { country: 'South Korea', nationality: 'South Korean', code: 'KR' },
  { country: 'Spain', nationality: 'Spanish', code: 'ES' },
  { country: 'Sri Lanka', nationality: 'Sri Lankan', code: 'LK' },
  { country: 'Sudan', nationality: 'Sudanese', code: 'SD' },
  { country: 'Sweden', nationality: 'Swedish', code: 'SE' },
  { country: 'Switzerland', nationality: 'Swiss', code: 'CH' },
  { country: 'Syria', nationality: 'Syrian', code: 'SY' },
  { country: 'Taiwan', nationality: 'Taiwanese', code: 'TW' },
  { country: 'Tajikistan', nationality: 'Tajikistani', code: 'TJ' },
  { country: 'Tanzania', nationality: 'Tanzanian', code: 'TZ' },
  { country: 'Thailand', nationality: 'Thai', code: 'TH' },
  { country: 'Tonga', nationality: 'Tongan', code: 'TO' },
  { country: 'Tunisia', nationality: 'Tunisian', code: 'TN' },
  { country: 'Turkey', nationality: 'Turkish', code: 'TR' },
  { country: 'Turkmenistan', nationality: 'Turkmen', code: 'TM' },
  { country: 'Uganda', nationality: 'Ugandan', code: 'UG' },
  { country: 'Ukraine', nationality: 'Ukrainian', code: 'UA' },
  { country: 'United Arab Emirates', nationality: 'Emirati', code: 'AE' },
  { country: 'United Kingdom', nationality: 'British', code: 'GB' },
  { country: 'United States', nationality: 'American', code: 'US' },
  { country: 'Uruguay', nationality: 'Uruguayan', code: 'UY' },
  { country: 'Uzbekistan', nationality: 'Uzbekistani', code: 'UZ' },
  { country: 'Vanuatu', nationality: 'Ni-Vanuatu', code: 'VU' },
  { country: 'Venezuela', nationality: 'Venezuelan', code: 'VE' },
  { country: 'Vietnam', nationality: 'Vietnamese', code: 'VN' },
  { country: 'Yemen', nationality: 'Yemeni', code: 'YE' },
  { country: 'Zambia', nationality: 'Zambian', code: 'ZM' },
  { country: 'Zimbabwe', nationality: 'Zimbabwean', code: 'ZW' },
];

export const NATIONALITIES: string[] = COUNTRIES.map((c) => c.nationality);
export const COUNTRY_NAMES: string[] = COUNTRIES.map((c) => c.country);

const CODE_BY_COUNTRY = new Map(COUNTRIES.map((c) => [c.country, c.code]));
const CODE_BY_NATIONALITY = new Map(COUNTRIES.map((c) => [c.nationality, c.code]));

export function flagCodeForCountry(value: string): string | undefined {
  return CODE_BY_COUNTRY.get(value.trim());
}

export function flagCodeForNationality(value: string): string | undefined {
  return CODE_BY_NATIONALITY.get(value.trim());
}
